#!/usr/bin/env python3
#
# Generate a sample SSH config file from bottle-pi.config
#

import yaml

with open('bottle-pi.config') as fh:
    configs = yaml.load(fh, Loader=yaml.SafeLoader)

for serial, system in configs['systems'].items():
    hostname = system['hostname']
    if hostname.split('-')[1] in ('4b', 'cm4', '5b', 'cm5'):
        # RAM alias for devices with different RAM configurations
        ram = system.get('features').get('ram').lower()
        real_hostname = hostname.replace('-rev', '-{}-rev'.format(ram))
        hosts = [hostname, real_hostname]
    else:
        real_hostname = hostname
        hosts = [hostname]

    print("""Host {}
  HostName {}
  User ubuntu
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ConnectTimeout 1
""".format((' ').join(hosts), real_hostname))
