#!/usr/bin/env python3
#
# Genereate a sample conserver config file from bottle-pi.config
#
import yaml

with open('bottle-pi.config') as fh:
    configs = yaml.load(fh, Loader=yaml.SafeLoader)

slots = {}
for serial, system in configs['systems'].items():
    hostname = system['hostname']
    ram = system['features']['ram']
    slot = system['slot']
    serialport = system['serialport']

    alias = hostname.replace('-rev', '-{}-rev'.format(ram.lower()))
    if slot in slots:
        slots[slot]['aliases'].extend([hostname, alias])
    else:
        slots[slot] = {
            'aliases': [hostname, alias],
            'device': serialport,
        }

print("""# Conserver configuration file

default * {
	master localhost;
	logfile /var/log/conserver/&.log;
	timestamp "";
	rw *;
	type device;
	baud 115200;
	parity none;
}
""")

for slot in slots:
    print("""console slot-{} {{
	aliases {};
	device {};
}}
""".format(slot, ','.join(slots[slot]['aliases']), slots[slot]['device']))

print("""access * {
	trusted localhost,gollum,smeagol;
}""")
