#!/usr/bin/env python3
#
# Generate a sample bash aliases file from bottle-pi.config
#

import os
import yaml

def print_aliases(alias, host, cli):
    cmds = {
        'reset': 'system-reset',
        'update': 'system-update',
        'pon': 'system-poweron',
        'poff': 'system-poweroff',
        'show': 'system-show',
    }
    print('alias sol-{}="console -M ozzy -p 3109 -U {}"'.format(alias, host))
    for cmd in cmds:
        print('alias {}-{}="{} ozzy:5000 {} {}"'.format(cmd, alias, cli,
                                                        cmds[cmd], host))

cli = os.path.abspath('bottle-pi-cli')

with open('bottle-pi.config') as fh:
    configs = yaml.load(fh, Loader=yaml.SafeLoader)

slots = {}
systems = []
for serial, system in configs['systems'].items():
    hostname = system['hostname']
    slot = system['slot']

    # Hostname alias
    print_aliases(hostname, hostname, cli)

    if hostname.split('-')[1] in ('4b', 'cm4', '5b'):
        # RAM alias for devices with different RAM configurations
        ram = system.get('features').get('ram').lower()
        print_aliases(hostname.replace('-rev', '-{}-rev'.format(ram)),
                      hostname, cli)

    if not slots.get(slot, False):
        # Slot alias
        slots[slot] = True
        print_aliases('rpi-slot{}'.format(slot), hostname, cli)

    print()
