#!/bin/bash -eu
#
# Genereate a sample conserver config file from bottle-pi.config
#

declare -a slots=()
declare -A aliases=()
declare -A device=()

while read -r x1 x2 x3 rest ; do
	if [ "${x1}${x2}" = "#Slot" ] ; then
		slot=${x3}
		slots+=("${slot}")
	fi
	if [ "${x1}" = "hostname:" ] ; then
		if [ -z "${aliases[${slot}]:-}" ] ; then
			aliases[${slot}]=${x2}
		else
			aliases[${slot}]=${aliases[${slot}]},${x2}
		fi
	fi
	if [ "${x1}" = "serialport:" ] ; then
		device[${slot}]=${x2}
	fi
done < <(cat bottle-pi.config)

cat <<EOF
# Conserver configuration file

default * {
	master localhost;
	logfile /var/log/conserver/&.log;
	timestamp "";
	rw *;
	type device;
	baud 115200;
	parity none;
}
EOF

while IFS= read -r slot ; do
	cat <<EOF

console slot-${slot} {
	aliases ${aliases[${slot}]};
	device ${device[${slot}]};
}
EOF
done < <(printf "%s\n" "${slots[@]}" | sort -nu)

cat <<EOF

access * {
	trusted localhost,gollum,smeagol;
}
EOF
