#!/usr/bin/env python3
#
# Generate a sample ser2net config yaml from bottle-pi.config
#
import yaml

with open('bottle-pi.config') as fh:
    configs = yaml.load(fh, Loader=yaml.SafeLoader)

print("""%YAML 1.1
---
# ser2net configuration file

define: &banner Connected to port \\N(\\d)\\r\\n
""")

slots = {}
for _, system in configs['systems'].items():
    slot = system['slot']
    serialport = system['serialport']
    tcpport = system['tcpport']

    if slot in slots:
        continue
    slots[slot] = 1

    print("""connection: &slot-{}
    accepter: tcp,{}
    connector: serialdev,{},115200N81
    options:
        banner: *banner
        kickolduser: true
""".format(slot, tcpport, serialport))
